slf4j:
  version: 1.7.32
pi4j:
  version: 2.1.1
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/sprinklerdatabase"
    username: "sprinklerserver"
    password: parabole1
    driver-class-name: org.postgresql.Driver
apiKeys:
  geo: "CxtK5Aq0lPJt1FR+o+NDAQ==HneU0PTvhzAxmk44"
  #https://api.openweathermap.org
  forecast: "&appid=de338ff9b1c030f6106b720bd64c0821"




