# Use postgres/example user/password credentials
# Use docker stack deploy -c docker-compose.yml postgres to deploy
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sprinklerserver
      POSTGRES_PASSWORD: parabole1
      POSTGRES_DB: sprinklerdatabase
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8082